before:
  hooks:
    - go mod tidy

builds:
  - id: e4client
    main: ./cmd/e4client/e4client.go
    binary: e4client
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
  - id: e4keygen
    main: ./cmd/e4keygen/e4keygen.go
    binary: e4keygen
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - id: e4client
    builds:
      - e4client
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - ./cmd/e4client/README.md
      - LICENSE
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

  - id: e4keygen
    builds:
      - e4keygen
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - ./cmd/e4keygen/README.md
      - LICENSE
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^scripts:"
      - "^test:"

release:
  draft: true
